---
title: "Features that are in alpha preview"
format: html
---

Depending on the version of Positron you are using, you can experiment with these features. They are in active development and are currently available in an experimental alpha preview.

## Positron Notebook Editor

The Positron Notebook Editor is a new way to create and edit notebooks. It is designed to be more intuitive and user-friendly than the traditional notebook editor. 

- **Requires**: Positron 2026.02.1 or later
- **To enable**: 
    1. Open the Command Palette (**CMD + Shift + P**)
    2. Search for "Positron: Enable Notebook Editor"
    3. Check the box
- **Read more**: [Positron Notebook Editor (Guide)](https://positron.posit.co/positron-notebook-editor.html)
- **Things to try**:
    - CMD + Shift + P then "View: Notebook Layout"
    - Toggle the kernal selector at the top of a notebook
    - Create object in a notebook cell, then explore them in the session pane and data explorer
    - Click the robot icon at the top of the Notebook to collaborate with AI on the notebook

---

## Inline Quarto Output

Positron will soon display the output of Quarto code cells inline, below each cell, as the RStudio IDE does. 

- **Requires**: Positron 2026.04.1 or later
- **To enable**: 
    1. Open the Command Palette (**CMD + Shift + P**) 
    2. Search for "Preferences: Open User Settings"
    2. Within the settings, search for "positron.quarto.inlineOutput.enabled"
    3. Check the box
- **Read more**: [Inline Outputs for Quarto and R Markdown Files](https://positron.posit.co/blog/posts/2026-04-06-april-newsletter/#inline-outputs-for-quarto-and-r-markdown-files)