---
title: "Load testing"
format: html
---

To help load test our infrastructure, do these tasks at roughly the same time as your classmates. **Be sure to record the zoom session.**

1. Run in the Positron Assistant chat window (in Ask mode with Claude 4 Sonnet Bedrock, which are the defaults):

> What went wrong? Can you fix it?

2. Apply the changes in your Editor.

3. Place your cursor in the final, empty code cell of `report.qmd`. Then press Ctrl/Cmd + I to open the Inline Positron Assistant editor. Ask the editor to:

> Make a colorful table that compares the ten countries with the highest overall rank.

4. Follow along to publish your document to Connect

5. Open the Command Palette (Ctrl/Cmd + Shift + P). Then type and run Open Databot. Click through the Help me Set Up Databot wizard.

6. Run the following in the Databot chat window.

> The csv files in my working directory contain data about multiple countries. Each file contains one year's worth of data from 2015-2019. Use the files to create a scatterplot of Happiness scores vs GDP. Include all of the years.

7. Click through several databot suggestions to further explore the data however your like.

8. Run /report to generate a quarto report of your session.

9. Open report-python.qmd. Run the first two code cells in order to produce an error. Start a new Positron Assistant chat in the sidebar by clicking `+`. Repeat step one.

10. Place your cursor in the code cell that makes a graph and press Ctrl/Cmd + I to open the inline editor. Ask Positron Assistant to

> Color the data point for the united states red and add a large label next to the point.